export const attendables = {
  present: [
    'appreciations',
    'curiosities',
    'emotions',
    'fears',
    'feelings',
    'frustrations',
    'ideas',
    'intuitions',
    'moments',
    'needs',
    'observations',
    'reactions',
    'sensations',
    'thoughts',
    'truths',
  ],
  future: [
    "artistic moves",
    "cravings",
    "desires",
    "experiences",
    "fantasies",
    "goals",
    "hopes",
    "moments",
    "reactions",
    "wishes",
  ],
  approaches: [
    "approaches",
    "habits",
    "meeting frames",
    "personas",
    "routines",
    "work routines",
  ],
  setups: [
    "places",
    "plans",
    "possibilities",
    "projects",
    "social events",
    "social interactions",
    "social situations",
    "workplaces",
  ],
  people: [
    "colleagues",
    "companions",
    "friends",
    "ongoing relationships",
    "partners",
    "people",
  ],
}

