export const attendables = {
  "inside me": [
    "appreciations",
    "confusions",
    "cravings",
    "curiosities",
    "desires",
    "emotions",
    "fantasies",
    "fears",
    "feelings",
    "frustrations",
    "goals",
    "hopes",
    "ideas",
    "intuitions",
    "moments",
    "needs",
    "observations",
    "personas",
    "reactions",
    "sensations",
    "thoughts",
    "truths",
    "wishes",
  ],
  "next actions": [
    "actions",
    "artistic moves",
    "experiences",
    "moments",
    "plans",
    "possibilities",
    "projects",
    "reactions",
    "social interactions",
  ],
  "social": [
    "colleagues",
    "companions",
    "conversations",
    "friends",
    "partners",
    "people",
    "personalities",
    "relationships",
    "social events",
    "social situations",
    "strangers",
  ],
  "lifestyles": [
    "approaches",
    "habits",
    "lifestyles",
    "meeting frames",
    "places",
    "routines",
    "work routines",
    "workplaces",
  ],
  "environment": [
    "coincidences",
    "contexts",
    "environments",
    "events",
    "experiences",
    "patterns",
    "places",
    "scenes",
    "situations",
    "surprises",
    "time",
  ]
}
